name: 3d-annotation-gui
channels:
  - conda-forge
dependencies:
  - python>=3.11,<3.14
  - numpy>=2.0
  - opencv
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - tk
  - pytables
  - pyyaml
  - pytest
